bundler_args: --without production development #rails-dev-boost: invalid byte sequence in US-ASCI

rvm: 1.9.3

before_script:
  - "cp config/database.yml.example config/database.yml 2>&1"
  - "cp config/app_secret_config.yml.example config/app_secret_config.yml 2>&1"
  - "bundle exec rake db:drop db:create db:schema:load --trace 2>&1"

script:
  - "bundle exec rspec spec"
