#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("github", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/github.rb", config.to_hash